#!/bin/sh

echo "Configuring zsh shell…"
chsh -s /bin/zsh

echo "Installing Homebrew…"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
./scripts/homebrew

echo "Installing Ruby…"
rbenv install 2.3.0
rbenv global 2.3.0
gem install bundler cocoapods cocoapods-keys cocoapods-stats cocoapods-deintegrate fastlane xcpretty fui synx

echo "Change Terminal Theme…"
open ./theme/developer.terminal

echo "Done."