#!/usr/bin/env bash

source $SCRIPTS_PATH/functions

info 'Installing Ruby'
rbenv install 2.3.1
rbenv global 2.3.1

info 'Installing Gems'
gem install bundler cocoapods danger fastlane xcpretty xcode-install
bundle config --global jobs `sysctl -n hw.ncpu`

info 'Change Terminal Theme'
open $DOTFILES_ROOT/theme/developer.terminal
