#!/usr/bin/env bash

function info() {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

function run() {
  sh $SCRIPTS_PATH/$1
}

function install_zsh() {
  chsh -s /bin/zsh
}

function install_brew() {
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew bundle --file=$SCRIPTS_PATH/Brewfile 
}

function install_gems() {
  gem install bundler cocoapods danger fastlane xcpretty
  bundle config --global jobs `sysctl -n hw.ncpu`
}

function install_dotfiles() {
  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 1 -name '.*' -not -path '*.git')
  do
    dst="$HOME/$(basename "${src}")"
    cp -R "$src" "$dst"
  done
}

function install_theme() {
osascript <<EOD

tell application "Terminal"

	local allOpenedWindows
	local initialOpenedWindows
	local windowID
	set themeName to "Developer"

	(* Store the IDs of all the open terminal windows. *)
	set initialOpenedWindows to id of every window

	(* Open the custom theme so that it gets added to the list
	   of available terminal themes (note: this will open two
	   additional terminal windows). *)
	do shell script "open '$THEME_PATH/" & themeName & ".terminal'"

	(* Wait a little bit to ensure that the custom theme is added. *)
	delay 1

	(* Set the custom theme as the default terminal theme. *)
	set default settings to settings set themeName

	(* Get the IDs of all the currently opened terminal windows. *)
	set allOpenedWindows to id of every window

	repeat with windowID in allOpenedWindows

		(* Close the additional windows that were opened in order
		   to add the custom theme to the list of terminal themes. *)
		if initialOpenedWindows does not contain windowID then
			close (every window whose id is windowID)

		(* Change the theme for the initial opened terminal windows
		   to remove the need to close them in order for the custom
		   theme to be applied. *)
		else
			set current settings of tabs of (every window whose id is windowID) to settings set themeName
		end if

	end repeat

end tell

EOD

}
