#!/usr/bin/env bash

source $SCRIPTS_PATH/functions

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update
brew upgrade

TAPS=(
  homebrew/bundle
  caskroom/cask
)

brew tap ${TAPS[@]}

info 'Installing brew dependencies'
brew bundle --file="$SCRIPTS_PATH/Brewfile"

info 'Installing cask dependencies'
brew bundle --file="$SCRIPTS_PATH/Caskfile"
