#!/bin/sh

brew update
brew upgrade

TAPS=(
    homebrew/dupes
    homebrew/versions
    caskroom/cask
    caskroom/versions
)

brew tap ${TAPS[@]}

FORMULAS=(
    rbenv
    ruby-build
    git
    libxml2
    libxslt
    libiconv
    kdiff3
    brew-cask
)
brew install ${FORMULAS[@]}

brew cleanup